syntax = "proto3"; //指定proto使用proto3语法，不指定默认是使用proto2

message BasePackage{
	int32 proto_code = 1;//协议码
	int32 unity_session_id=2;//unity端的sessionID.
	int32 gate_session_id=3;//网关服务器与游戏服务器连接的sessionID
	bytes data = 10;//数据
}


message RegistReq{
	string user_name =1;//用户名
	string phone_num=2;//手机号
	string password = 3;//密码；
}

//登录
message LoginReq{
	string user_name=1;//用户名
	string password= 2;//密码
}

//获取服务器列表
message GetServerListReq{
	int32 server_id=1;//
}

//登录游戏服务器
message LoginGameServerReq{
	int32 account_id = 1;//
	int32 game_server_id=2;//
}

//创建角色请求数据
message CreateRoleReq{
	int32 account_id = 1;//
	int32 game_server_id=2;//所属的服务器
	string nickname =3;//昵称
	int32 job_id=4;//职业
}

message StartGameReq{
	int32 role_id = 1;//角色id
}

message EnterWroldReq{
	int32 role_id = 1;//角色id
}

//角色购买商品请求参数
message RoleBuyItemReq{
	int32 role_id = 1;//角色id
	int32 item_id = 2;
	int32 count = 3;
}

//角色退出游戏请求参数
message RoleExitGameReq{
	int32 role_id = 1;//角色id
}

//角色请求移动背包格子参数
message KnapsackSlotMoveReq{
	int32 role_id = 1;//角色id
	int32 drag_slot_no = 2;
	int32 target_slot_no = 3;
}

message KnapsackItemSplitReq{
	int32 role_id = 1;//角色id
	int32 slot_no = 2;//
}

//整理背包请求参数
message KnapsackClearUpReq{
	int32 role_id = 1;//角色id
}

//穿戴装备请求参数
message PutOnEquipReq{
	int32 role_id = 1;//角色id
	int32 wear_equip_slot_no = 2;
	int32 knapsack_slot_no = 3;
}

//卸载装备请求参数
message UnloadEquipReq{
	int32 role_id = 1;//角色id
	int32 wear_equip_slot_no = 2;
	int32 knapsack_slot_no = 3;
}

//角色移动请求参数
message RoleMoveReq{
	int32 role_id = 1;//角色id
	float pos_x = 2;
	float pos_y =3;
	float pos_z = 4;
	float rotate_y = 5;
	int64 server_time = 6;//预留字段， 在进行角色同步的时候， 延迟补偿
}

message RoleChangeStateReq{
	int32 role_id = 1;//角色id
	int32 state = 2;
}