syntax = "proto3"; //指定proto使用proto3语法，不指定默认是使用proto2


enum CmdCode{
	Succeed = 0;//请求成功
	AcctExist = 1;//账号已存在
	ServerError=2;//服务端错误
	AcctNotExist = 3;//账号不存在
	PasswordError= 4;//密码错误
	AcctDisable = 5;//账号禁用
	ReqParamError= 6;//请求参数错误
	NicknameExist = 7;//昵称已存在
	UserNameIllegal = 8;//用户名不合法
	PhoneNumIllegal= 9 ;//手机号码不合法
	PasswordIllegal=10;//密码不合法
	UserOftenLogin=11;//用户频繁登录
	RoleNotExist = 12;//角色不存在
	MoneyDeficit = 13;//游戏币不足
	KnapsackFull = 14;//背包已满
	AcctHasLogin = 15;//账号已登录
}


message ErrMsg{
	CmdCode cmd_code = 1;//错误码
}

message RegistRet{
	CmdCode cmd_code = 1;//表示注册是否成功
}

message LoginRet{
	CmdCode cmd_code = 1;//表示登录是否成功
	GameServer game_server=2;//表示最后登录的服务器
	int32 account_id = 3;//用户id
}

message GameServer{
	int32 server_id = 1;//服务器id，
	string server_name=2;//名称
	int32 run_state = 3;//运行状态
	int32 is_new = 4;//是否是新服
	string ip_host=5;//ip
	int32 prot = 6;//端口
}

message GetServerListRet{
	CmdCode cmd_code = 1;//表示请求是否成功
	repeated GameServer game_servers=2;//服务器列表
}

message LoginGameServerRet{
	CmdCode cmd_code = 1;//表示请求是否成功
	CreateRoleRet create_role_info = 2;//已创建的角色
}

message CreateRoleRet{
	CmdCode cmd_code = 1;//表示创建角色是否成功
	int32 role_id= 2;//角色ID
	string nickname= 3;//昵称
	int32 job_id = 4;
	int32 level = 5;
}

message StartGameRet{
	CmdCode cmd_code = 1;//表示请求是否成功
	//角色的所有属性信息，角色有很多类下，主角，其他玩家，NPC，怪兽等等。
	MainRoleInfo main_role_info = 2;
}

//角色基础信息
message RoleBaseInfo{
	int32 role_id = 1;
	int32 account_id = 17;
	string nickname = 2;
	int32 level = 3;
	int32 job_id = 16;
	int32 max_hp = 4;
	int32 curr_hp = 5;
	int32 max_mp= 6;
	int32 curr_mp = 7;
	int32 akt = 8;
	int32 def = 9;
	int32 crit = 10;
	int32 dodge = 11;
	int32 hit = 12;
	int32 penet = 13;
	string pos = 14;
	int32 map_id = 15;
}

//主角信息
message MainRoleInfo{
	RoleBaseInfo base_info = 1;
	int32 money=3;
	int32 exp = 5;
	int32 skill_up_point= 6;
	string camera_offset = 7;
	int32 server_id = 8;
}

//返回的角色所有技能信息数据
message RoleSkillInfoRet{
	CmdCode cmd_code = 1;//表示请求是否成功
	int32 role_id = 3;
	repeated RoleSkillInfo role_skill_info_lst = 2;
}

//角色的技能信息
message RoleSkillInfo{
	int32 skill_id = 1;
	int32 level = 2;
	string bind_key = 3;
}

//角色的背包数据
message RoleKnapsackInfoRet{
	CmdCode cmd_code = 1;//表示请求是否成功
	int32 role_id = 3;
	repeated RoleKnapsackSlot role_knapsack_slot_lst = 2;
}

//每个背包格子数据
message RoleKnapsackSlot{
	int32 slot_no = 1;//背包格子编号
	int32 item_id= 2;//物品id
	int32 count = 3;
}

//角色穿戴的装备信息列表数据
message RoleWearEquipInfoRet{
	CmdCode cmd_code = 1;//表示请求是否成功
	int32 role_id = 3;
	repeated RoleWearEquipSlot role_wear_equip_lst = 2;
}

//每个穿戴的装备格子数据
message RoleWearEquipSlot{
	int32 slot_no = 1;//装备格子编号
	int32 item_id= 2;//物品id
	int32 type = 3;
}

//角色购买商品返回数据
message RoleBuyItemRet{
	CmdCode cmd_code = 1;//表示请求是否成功
	int32 money = 2;
	RoleKnapsackSlot knapsack_slot = 3;
}

message PutOnEquipRet{
	CmdCode cmd_code = 1;//表示请求是否成功
	RoleWearEquipSlot wear_equip_slot = 2;
	RoleKnapsackSlot knapsack_slot = 3;
	RoleBaseInfo base_info = 4;
}

message UnloadEquipRet{
	CmdCode cmd_code = 1;//表示请求是否成功
	RoleWearEquipSlot wear_equip_slot = 2;
	RoleKnapsackSlot knapsack_slot = 3;
	RoleBaseInfo base_info = 4;
}

message OtherRoleMoveRet{
	int32 role_id = 1;//角色id
	float pos_x = 2;
	float pos_y =3;
	float pos_z = 4;
	float rotate_y = 5;
	int64 server_time = 6;//预留字段， 在进行角色同步的时候， 延迟补偿
}

message OtherRoleChangeStateRet{
	int32 role_id = 1;//角色id
	int32 state = 2;
}

message OtherRoleExitGameRet{
	int32 role_id = 1;//角色id
}